spring:
  security:
    jwt:
      secretKey: ${JWT_SECRET_KEY}
      token:
        # 1 day
        expiration: 3600000
      refreshToken:
        # 1 week
        expiration: 604800000
      temporaryToken:
        secretKey: ${JWT_SECRET_TEMPORARY_KEY}
        # 30 minutes
        expiration: 1800000

  application:
    name: wedding-invitations-app
    version: @project.version@

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
      pool-name: WeddingAppHikariCP

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USER}
    origin: ${EMAIL_FORM_ORIGIN}
    password: ${EMAIL_PASS}
    port: 587
    properties:
      "[mail.smtp.timeout]": 10000
      "[mail.smtp.connectiontimeout]": 10000
      "[mail.smtp.writetimeout]": 10000
      "[mail.smtp.ssl.enable]" : true,
      "[mail.smtp.ssl.required]" : true

