spring:
  security:
    jwt:
      secretKey: 3bfaa3e8057fee94827a7749d561b20146937d32e2b784c496347a0ca1235136
      token:
        # 1 day
        expiration: 3600000
      refreshToken:
        # 1 week
        expiration: 604800000

  application:
    name: wedding-invitations-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_my_wedding_app
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
      pool-name: WeddingAppHikariCP
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

